CREATE TABLE [dbo].[Applications]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
	[UserId] NVARCHAR (128) NOT NULL,
	[ApplicationAlias] NVARCHAR(256) NOT NULL,
	[CreateDate] DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
	[UpdateDate] DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
	[DefaultEncryption] VARCHAR(1) NOT NULL DEFAULT 'N'
)
