CREATE TABLE [dbo].[Applications]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
	[UserId] NVARCHAR (128) NOT NULL,
	[ApplicationAlias] NVARCHAR(256) NOT NULL,
	[CreateDate] DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
	[UpdateDate] DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
	[DefaultEncryption] BIT NOT NULL DEFAULT 0, 
    CONSTRAINT [FK_Applications_ToUsers] FOREIGN KEY ([UserId]) REFERENCES [Users]([Id])
)
