CREATE TABLE [dbo].[Users]
(
	[Id] NVARCHAR (128) NOT NULL PRIMARY KEY,
	[FirstName] NVARCHAR(256) NOT NULL,
	[LastName] NVARCHAR(256) NOT NULL,
	[EmailAddress] NVARCHAR(256) NOT NULL,
	[CreateDate] DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
	[UpdateDate] DATETIME2 NOT NULL DEFAULT GETUTCDATE()
)
